version: '3.7'
services:

  api-gateway:
    build: ./
    container_name: api-gateway
    networks:
    - core
    - postgres
    env_file:
    - .env

networks:
  core:
    name: core
  postgres:
    name: postgres