version: '3.7'
services:

  api-gateway-1:
    build:
      context: ../../
      dockerfile: cmd/api-gateway/Dockerfile
    container_name: api-gateway-1
    networks:
    - core
    - postgres
    env_file:
    - .env

  api-gateway-2:
    build:
      context: ../../
      dockerfile: cmd/api-gateway/Dockerfile
    container_name: api-gateway-2
    networks:
    - core
    - postgres
    env_file:
    - .env

  api-gateway-3:
    build:
      context: ../../
      dockerfile: cmd/api-gateway/Dockerfile
    container_name: api-gateway-3
    networks:
    - core
    - postgres
    env_file:
    - .env

networks:
  core:
    name: core
  postgres:
    name: postgres