version: '3.7'
services:

  prometheus:
    build: ./prometheus
    container_name: prometheus
    networks:
    - core
    expose:
    - 9090
    volumes:
      - prometheus:/prometheus
    command:
      - '--web.external-url=http://localhost:9090/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
    - core
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    expose:
    - 9100

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres-exporter
    networks:
    - core
    - postgres
    env_file:
    - .env

  container-exporter:
    image: prom/container-exporter
    container_name: container-exporter
    volumes:
      - /sys/fs/cgroup:/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - core
    - postgres
    env_file:
    - .env

networks:
  core:
    name: core
  postgres:
    name: postgres

volumes:
  prometheus: