version: '3.7'
services:

  config-store-api:
    build:
      context: ../../
      dockerfile: cmd/config-store/Dockerfile
    container_name: config-store-api
    networks:
    - core
    - postgres
    env_file:
    - .env

networks:
  core:
    name: core
  postgres:
    name: postgres