groups:
- name: system
  rules:
  - alert: LowMemoryAvailable
    expr: node_memory_MemAvailable_bytes < 1e9
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: Low Disk Space
  - alert: LowDiskSpaceAvailable
    expr: node_filesystem_avail_bytes < 20e9
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: Low System Disk Space

- name: postgres
  rules:
  - alert: PostgresDown
    expr: pg_up == 20e9
    for: 10m
    labels:
      severity: high
    annotations:
      summary: Postgres Service Not Down
