global:
  scrape_interval:     60s # By default, scrape targets every 15 seconds.

rule_files:
  - /etc/prometheus/rules.yml
  - /etc/prometheus/alerts.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 60s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'jaeger-agent'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    static_configs:
      - targets: ['jaeger-agent:14271']

  - job_name: 'jaeger-collector'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    static_configs:
      - targets: ['jaeger-collector:14269']

  - job_name: 'jaeger-query'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    static_configs:
      - targets: ['jaeger-query:16687']

  - job_name: 'postgres'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    static_configs:
      - targets: ['postgres-exporter:9187']